language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - "pip install coverage coveralls"
  - "pip install -r test_requirements.txt"
  - "pip install git+https://github.com/landscapeio/pylint-plugin-utils.git@develop"
  - "pip install --editable ."
script:
  coverage run test/test_func.py
after_success:
  coveralls