language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install coverage coveralls pylint-plugin-utils -r test_requirements.txt
  - pip install --editable .
script:
  coverage run test/test_func.py
after_success:
  coveralls
